service: product-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: development
  region: us-east-1

functions:
  getProductsList:
    handler: src/functions/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: src/functions/getProductsById.getProductsById
    events:
      - http:
          path: /products/{id}
          method: get
          cors: true