service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: development
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::${ssm:/system/api/IMPORT_SERVICE_BUCKET_NAME}"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::${ssm:/system/api/IMPORT_SERVICE_BUCKET_NAME}/*"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource:
            - "arn:aws:sqs:us-east-1:448342942052:ProductsSQSQueue"
        - Effect: "Allow"
          Action:
            - "sns:*"
          Resource:
            - "*"

functions:
  importProductsFile:
    handler: src/functions/importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            arn: "arn:aws:lambda:us-east-1:448342942052:function:authorization-service-development-basicAuthorizer"
            identitySource: method.request.header.Authorization
            type: token
  importFileParser:
    handler: src/functions/importFileParser.importFileParser
    events:
      - s3:
          bucket: ${ssm:/system/api/IMPORT_SERVICE_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true


